### DISCUSSION TITLE
Are volumes supported?

### DISCUSSION THREAD

**Discussion by jritsema** [portainer/k2d#71] [Q&A]
Hello!  This is a super interesting project.  I tried a quick test to deploy the prometheus node exporter on a `RPI 2 Model B (armv7)` and got the following error.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: exporter
        image: prom/node-exporter-linux-armv7:v1.0.1
        command:
          - "--path.rootfs=/host"
        securityContext:
          pidMode: "host"

        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory

```

results in this error

```
--path.rootfs=/host: no such file or directory
```

full error

```
{"status":"Status: Image is up to date for prom/node-exporter-linux-armv7:v1.0.1"}
2023-10-07T20:34:16.512Z	ERROR	controller/controller.go:190	unable to create deployment	{"error": "Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"--path.rootfs=/host\\\": stat --path.rootfs=/host: no such file or directory\": unknown", "request_id": "231a1393-f970-43ee-9a29-e7c6dd4f83c3"}
github.com/portainer/k2d/internal/controller.(*OperationController).processOperation
	/root/workspace/k2d/internal/controller/controller.go:190
github.com/portainer/k2d/internal/controller.(*OperationController).processPriorityOperations
	/root/workspace/k2d/internal/controller/controller.go:165
github.com/portainer/k2d/internal/controller.(*OperationController).processOperationQueue
	/root/workspace/k2d/internal/controller/controller.go:154
```

What am I doing wrong?  Or is this volume config not supported?

**Comment by jritsema** [comment]
Ah, never mind.  I see from the [docs](https://docs.k2d.io/known-limitations) that:

```Persistent Volume creation is only supported via Persistent Volume Claim```

**Comment by deviantony** [comment]
Hi @jritsema 

`hostPath` volumes are also supported by k2d !

Look at this manifest for example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
spec:
  selector:
    matchLabels:
      app: influxdb
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:1.7.4
          name: influxdb
          ports:
            - containerPort: 8086
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-data
            - mountPath: /etc/influxdb/influxdb.conf
              name: influxdb-config
              subPath: influxdb.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secrets
      volumes:
        - name: influxdb-data
          hostPath:
            path: /var/lib/k2d/data/influxdb-data
        - name: influxdb-config
          configMap:
            name: influxdb-config

---
[...]
```

This info is also available in the list of supported properties for the `Pod` object: https://docs.k2d.io/supported-resources-and-operations#pod
