### ISSUE TITLE
Support for container Command and Args properties

### ISSUE THREAD

**Issue by deviantony** [portainer/k2d#23]
Add support for the Command and Args properties of a container.

This will allow to deploy pods that leverages these properties such as:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done;"]

```
