### ISSUE TITLE
Bind mount failed

### ISSUE THREAD

**Issue by rothgar** [portainer/k2d#91]
I'm trying to create a pod via kubectl with this spec
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  automountServiceAccountToken: false
```
but when I apply it the docker container gets created but isn't running. I see this error in the k2d logs
```
ERROR   controller/controller.go:174    unable to create pod   {"error": "Error response from daemon: Bind mount failed: '/var/lib/k2d/secrets/k2d-k2d-serviceaccount-k2dsec-token' does not exists", "request_id": "5af66fd9-7991-4ee6-92c8-5961713f962b"}
```
The pod stays in an Unknown state
```
k get pods
NAME            READY   STATUS    RESTARTS   AGE
nginx           0/1     Unknown   0          3m13s
```

If I manually create an empty file in that location it continues but errors on k2d-k2d-serviceaccount-k2dsec-ca.crt not existing. I can manually create an empty file for that too but it won't continue past that error.
```
2024-10-16T17:49:18.840Z        ERROR   controller/controller.go:174    unable to create pod   {"error": "Error response from daemon: Bind mount failed: '/var/lib/k2d/secrets/k2d-k2d-serviceaccount-k2dsec-ca.crt' does not exists", "request_id": "737ca7ef-6aba-45fa-9e81-f9e1fc571960"}
github.com/portainer/k2d/internal/controller.(*OperationController).processOperation
        /root/workspace/k2d/internal/controller/controller.go:174 github.com/portainer/k2d/internal/controller.(*OperationController).processPriorityOper
ations
        /root/workspace/k2d/internal/controller/controller.go:165 github.com/portainer/k2d/internal/controller.(*OperationController).processOperationQueue
```
